In [9]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [6]:
import numpy as np

## 合并两个list或数组

In [6]:
x = [1,2,3]
y = [4,5,6]
x,y

([1, 2, 3], [4, 5, 6])

In [18]:
v = np.vstack((x,y))
v
v.shape

array([[1, 2, 3],
       [4, 5, 6]])

(2, 3)

In [19]:
h = np.hstack((x,y))
h
h.shape

array([1, 2, 3, 4, 5, 6])

(6,)

In [16]:
np.concatenate((x,y), axis=0)

array([1, 2, 3, 4, 5, 6])

In [29]:
A = np.array(x)
B = A[:,np.newaxis] #在列方向上添加维度
B

array([[1],
       [2],
       [3]])

In [22]:
C = np.array(y)
D = C[:,np.newaxis] #在行方向上添加维度
D

array([[4],
       [5],
       [6]])

In [25]:
np.vstack((B, D))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [26]:
np.hstack((B, D))

array([[1, 4],
       [2, 5],
       [3, 6]])

## 两个list的加法

In [10]:
x = [1,2,3,4]
y = [3,6,12,9]
list(map(lambda x: x[0]-x[1], zip(x, y)))
x+y

[-2, -4, -9, -5]

[1, 2, 3, 4, 3, 6, 12, 9]

In [11]:
v1 = np.array([1,2,3,4])
v2 = np.array([3,6,12,9])
v1-v2

array([-2, -4, -9, -5])

## 读取zip文件里的csv

In [13]:
import pandas as pd
import zipfile
import urllib.request

# download the zip file by using urlib.request.urlretrieve
url = 'https://d396qusza40orc.cloudfront.net/rprog/data/quiz1_data.zip'  
urllib.request.urlretrieve(url, "quiz.zip")

('quiz.zip', <http.client.HTTPMessage at 0x2b433d9a390>)

In [14]:
zf = zipfile.ZipFile('quiz1_data.zip') 
df = pd.read_csv(zf.open('hw1_data.csv'))

In [15]:
df.columns

Index(['Ozone', 'Solar.R', 'Wind', 'Temp', 'Month', 'Day'], dtype='object')

In [16]:
df.shape
df.ndim
df.dtypes

(153, 6)

2

Ozone      float64
Solar.R    float64
Wind       float64
Temp         int64
Month        int64
Day          int64
dtype: object

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 153 entries, 0 to 152
Data columns (total 6 columns):
Ozone      116 non-null float64
Solar.R    146 non-null float64
Wind       153 non-null float64
Temp       153 non-null int64
Month      153 non-null int64
Day        153 non-null int64
dtypes: float64(3), int64(3)
memory usage: 7.2 KB


In [18]:
df.describe()

Ozone     Solar.R        Wind        Temp       Month         Day
count  116.000000  146.000000  153.000000  153.000000  153.000000  153.000000
mean    42.129310  185.931507    9.957516   77.882353    6.993464   15.803922
std     32.987885   90.058422    3.523001    9.465270    1.416522    8.864520
min      1.000000    7.000000    1.700000   56.000000    5.000000    1.000000
25%     18.000000  115.750000    7.400000   72.000000    6.000000    8.000000
50%     31.500000  205.000000    9.700000   79.000000    7.000000   16.000000
75%     63.250000  258.750000   11.500000   85.000000    8.000000   23.000000
max    168.000000  334.000000   20.700000   97.000000    9.000000   31.000000

In [19]:
df.head(2)

Ozone  Solar.R  Wind  Temp  Month  Day
0   41.0    190.0   7.4    67      5    1
1   36.0    118.0   8.0    72      5    2

In [21]:
len(df) #df的行数

153

In [22]:
df.tail(2)

Ozone  Solar.R  Wind  Temp  Month  Day
151   18.0    131.0   8.0    76      9   29
152   20.0    223.0  11.5    68      9   30

In [26]:
df.iloc[47-1] #第47行，因为index是从0开始的，所以要-1

Ozone       21.0
Solar.R    191.0
Wind        14.9
Temp        77.0
Month        6.0
Day         16.0
Name: 46, dtype: float64

In [45]:
sum(pd.isnull(df.Ozone)) #缺失值有37个
pd.isnull(df.Ozone).sum()
df.Ozone.isnull().sum()

37

37

37

In [39]:
sum(pd.isnull(df['Solar.R']))

7

In [43]:
df.isnull().sum()

Ozone      37
Solar.R     7
Wind        0
Temp        0
Month       0
Day         0
dtype: int64

In [46]:
df.Ozone.mean() #Ozone列的均值

42.12931034482759

In [47]:
df.mean() # 每列的均值,自动删除缺失值

Ozone       42.129310
Solar.R    185.931507
Wind         9.957516
Temp        77.882353
Month        6.993464
Day         15.803922
dtype: float64

In [51]:
df1 = df[(df.Ozone>31) & (df.Temp>90)]
# 这里每个条件需要加上括号，不然出错
df1['Solar.R'].mean()

212.8

In [52]:
df2 = df[(df.Month == 6)]
df2.Temp.mean()

79.1

In [59]:
df3 = df[(df.Month==5) & (pd.notnull(df.Ozone))]
df3.Ozone.max()

115.0

## 定义函数

In [75]:
def cube(x,n):
    return (x**n)
   
cube(3,4)

81

In [76]:
cube(2,3)

8

## 分析Iris数据集

In [89]:
from sklearn.datasets import load_iris

iris = load_iris()
data = pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                     columns= iris['feature_names'] + ['species'])
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0      0.0  
1      0.0  
2      0.0  
3      0.0  
4      0.0

In [90]:
load_iris().target_names
load_iris().feature_names

array(['setosa', 'versicolor', 'virginica'], 
      dtype='<U10')

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [93]:
data.species.unique()

array([ 0.,  1.,  2.])

In [94]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
sepal length (cm)    150 non-null float64
sepal width (cm)     150 non-null float64
petal length (cm)    150 non-null float64
petal width (cm)     150 non-null float64
species              150 non-null float64
dtypes: float64(5)
memory usage: 5.9 KB


In [96]:
dict(zip(data.species.unique(), load_iris().target_names))

{0.0: 'setosa', 1.0: 'versicolor', 2.0: 'virginica'}

In [107]:
# 将哑变量的值替换为分类标签
data['Spec'] = pd.Categorical(data.species.replace({0:'setosa', 1:'versicolor',2:'virginica'}))
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
sepal length (cm)    150 non-null float64
sepal width (cm)     150 non-null float64
petal length (cm)    150 non-null float64
petal width (cm)     150 non-null float64
species              150 non-null float64
Spec                 150 non-null category
dtypes: category(1), float64(5)
memory usage: 6.2 KB


In [108]:
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species    Spec  
0      0.0  setosa  
1      0.0  setosa  
2      0.0  setosa  
3      0.0  setosa  
4      0.0  setosa

In [110]:
data['code']=data.Spec.cat.codes
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species    Spec  code  
0      0.0  setosa     0  
1      0.0  setosa     0  
2      0.0  setosa     0  
3      0.0  setosa     0  
4      0.0  setosa     0

In [129]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 7 columns):
sepal length (cm)    150 non-null float64
sepal width (cm)     150 non-null float64
petal length (cm)    150 non-null float64
petal width (cm)     150 non-null float64
species              150 non-null float64
Spec                 150 non-null category
code                 150 non-null int8
dtypes: category(1), float64(5), int8(1)
memory usage: 6.3 KB


In [112]:
sum(data.species == data.code)

150

In [114]:
data.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'species', 'Spec', 'code'],
      dtype='object')

In [123]:
dt = data[data.Spec=='virginica']
dt.iloc[:,0].mean()
dt['sepal length (cm)'].mean()

6.587999999999998

6.587999999999998

In [127]:
data.iloc[:,:4].mean()

sepal length (cm)    5.843333
sepal width (cm)     3.054000
petal length (cm)    3.758667
petal width (cm)     1.198667
dtype: float64

In [128]:
data.groupby('Spec').mean()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
Spec                                                                 
setosa                  5.006             3.418              1.464   
versicolor              5.936             2.770              4.260   
virginica               6.588             2.974              5.552   

            petal width (cm)  species  code  
Spec                                         
setosa                 0.244      0.0     0  
versicolor             1.326      1.0     1  
virginica              2.026      2.0     2

In [130]:
data.groupby('Spec').max()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
Spec                                                                 
setosa                    5.8               4.4                1.9   
versicolor                7.0               3.4                5.1   
virginica                 7.9               3.8                6.9   

            petal width (cm)  species  code  
Spec                                         
setosa                   0.6      0.0     0  
versicolor               1.8      1.0     1  
virginica                2.5      2.0     2

In [132]:
data.Spec.value_counts()

virginica     50
versicolor    50
setosa        50
Name: Spec, dtype: int64

## 随机种子，随机数

In [140]:
np.random.seed(1)
np.random.poisson(2, 5) #产生5个服从泊松分布的随机数
np.round(np.random.normal(0,1, 10),4)

array([2, 1, 0, 1, 2])

array([-1.017 ,  0.6374, -0.8599,  1.7726, -1.1104,  0.1812,  0.5643,
       -0.5665,  0.73  ,  0.373 ])

In [142]:
np.random.choice([0,1],10)

array([1, 1, 0, 1, 0, 0, 1, 1, 0, 1])

In [143]:
np.array([0,1]*5)

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])